//! Guards the documented surface against silent drift.
//!
//! The reference pages under `docs/reference/` describe the CLI and the Lua API
//! by hand. Prose cannot be verified, but its subject can: this records the
//! surface itself and fails when it moves, so a renamed flag or a new Lua
//! function is a failing test rather than something a reader discovers.

use std::fmt::Write as _;
use std::path::PathBuf;

use clap::CommandFactory as _;

const SNAPSHOT: &str = "tests/fixtures/surface-inventory.txt";

/// Lua that walks the `wombat` table and publishes what it finds, so the
/// inventory reflects natives registered by Rust rather than only what
/// `lua/wombat/init.lua` declares literally.
///
/// `host` and `target` are recorded but not descended into: they are observed
/// machine facts whose shape differs per platform, and pinning them would make
/// this snapshot fail on a machine other than the one that wrote it. Read-only
/// proxies such as `w.rungs` appear without their children, since they expose
/// nothing to `pairs`.
const WALK: &str = r#"
local w = require("wombat")
local opaque = { host = true, target = true }
local lines = {}
local function walk(value, prefix, depth)
    if depth > 2 then return end
    local names = {}
    for key in pairs(value) do
        if type(key) == "string" and key:sub(1, 1) ~= "_" then names[#names + 1] = key end
    end
    table.sort(names)
    for _, key in ipairs(names) do
        local child = value[key]
        local path = prefix .. "." .. key
        lines[#lines + 1] = path .. " " .. type(child)
        if type(child) == "table" and not (depth == 0 and opaque[key]) then
            walk(child, path, depth + 1)
        end
    end
end
walk(w, "w", 0)
w.generate("inventory", { content = table.concat(lines, "\n"), to = "inventory" })
"#;

fn repository_path(relative: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(relative)
}

fn command_inventory() -> String {
    fn visit(command: &clap::Command, prefix: &str, out: &mut String) {
        let path = if prefix.is_empty() {
            command.get_name().to_string()
        } else {
            format!("{prefix} {}", command.get_name())
        };
        let mut arguments: Vec<String> = command
            .get_arguments()
            .map(|argument| {
                let long = argument
                    .get_long()
                    .map_or_else(|| argument.get_id().to_string(), |long| format!("--{long}"));
                match argument.get_short() {
                    Some(short) => format!("-{short}/{long}"),
                    None => long,
                }
            })
            .collect();
        arguments.sort();
        let _ = writeln!(out, "{path} [{}]", arguments.join(" "));
        let mut children: Vec<&clap::Command> = command.get_subcommands().collect();
        children.sort_by_key(|child| child.get_name());
        for child in children {
            visit(child, &path, out);
        }
    }

    let mut out = String::new();
    visit(&super::Cli::command(), "", &mut out);
    out
}

fn lua_inventory() -> String {
    let temporary = tempfile::tempdir().expect("temporary repository");
    let root = temporary.path().join("source");
    std::fs::create_dir_all(&root).expect("source directory");
    std::fs::write(root.join("wombat.lua"), WALK).expect("root configuration");

    let build_dir = temporary.path().join("build");
    wombat::build(wombat::BuildOptions::new(&root, &build_dir)).expect("surface walk builds");
    let mut inventory = std::fs::read_to_string(build_dir.join("tree/inventory"))
        .expect("surface walk publishes an inventory");
    inventory.push('\n');
    inventory
}

#[test]
fn documented_surface_has_not_drifted() {
    let actual = format!(
        "# Generated by `documented_surface_has_not_drifted`. Do not edit by hand.\n\
         # Refresh with: WOMBAT_BLESS_SURFACE=1 cargo test --bins documented_surface\n\n\
         [cli]\n{}\n[lua]\n{}",
        command_inventory(),
        lua_inventory()
    );
    let path = repository_path(SNAPSHOT);

    if std::env::var_os("WOMBAT_BLESS_SURFACE").is_some() {
        std::fs::write(&path, &actual).expect("refresh the surface snapshot");
        return;
    }

    let expected = std::fs::read_to_string(&path).unwrap_or_default();
    assert_eq!(
        actual, expected,
        "\n\nWombat's CLI or Lua surface changed.\n\
         Update the reference pages that describe it:\n  \
         docs/reference/cli.md\n  docs/reference/lua.md\n\
         and any concept or how-to page that mentions the affected entry.\n\
         Then refresh this snapshot:\n  \
         WOMBAT_BLESS_SURFACE=1 cargo test --bins documented_surface\n\n\
         This gate only notices that the surface moved; it cannot tell whether\n\
         the prose is now correct.\n"
    );
}
