local w = require("wombat")

w.module.from(".local")
w.install("wombat-tools")
w.generate("wombat-build.txt", {
    content = "generated directly by Lua\n",
})
w.build.task("generate.py", {
    message = "generated by a conventional Python task",
}, {
    name = "example",
})
w.build.task("validate.sh", {}, {
    name = "validation",
    cache = false,
})
